
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_LED_DEVICE_ID,
		XPAR_GPIO_LED_BASEADDR,
		XPAR_GPIO_LED_INTERRUPT_PRESENT,
		XPAR_GPIO_LED_IS_DUAL
	},
	{
		XPAR_GPIO_SWITCH_DEVICE_ID,
		XPAR_GPIO_SWITCH_BASEADDR,
		XPAR_GPIO_SWITCH_INTERRUPT_PRESENT,
		XPAR_GPIO_SWITCH_IS_DUAL
	},
	{
		XPAR_TXRX_CONTROL_DEVICE_ID,
		XPAR_TXRX_CONTROL_BASEADDR,
		XPAR_TXRX_CONTROL_INTERRUPT_PRESENT,
		XPAR_TXRX_CONTROL_IS_DUAL
	},
	{
		XPAR_TXRX_STATUS_DEVICE_ID,
		XPAR_TXRX_STATUS_BASEADDR,
		XPAR_TXRX_STATUS_INTERRUPT_PRESENT,
		XPAR_TXRX_STATUS_IS_DUAL
	}
};


