
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xscugic.h"

/*
* The configuration table for devices
*/

XScuGic_Config XScuGic_ConfigTable[XPAR_XSCUGIC_NUM_INSTANCES] =
{
	{
		XPAR_VERSAL_CIPS_0_PSPMC_0_PSV_ACPU_GIC_DEVICE_ID,
		XPAR_VERSAL_CIPS_0_PSPMC_0_PSV_ACPU_GIC_BASEADDR,
		XPAR_VERSAL_CIPS_0_PSPMC_0_PSV_ACPU_GIC_DIST_BASEADDR,
		{{0}}		/**< Initialize the HandlerTable to 0 */
	}
};


