
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_GT_SIGS_0_DEVICE_ID,
		XPAR_AXI_GPIO_GT_SIGS_0_BASEADDR,
		XPAR_AXI_GPIO_GT_SIGS_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_GT_SIGS_0_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_GT_SIGS_1_DEVICE_ID,
		XPAR_AXI_GPIO_GT_SIGS_1_BASEADDR,
		XPAR_AXI_GPIO_GT_SIGS_1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_GT_SIGS_1_IS_DUAL
	}
};


